name = "MiloCraft4Ever"
author = "chester"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65dc77fe0f0d8a92fa2f565880161fd570f3a7e051bdf0da731345b8798cb7b9"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
