name = "MiloCraft4Ever"
author = "chester"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f313f8c2814a72530b30cd0d7f3271e8d28143c2b3fb84a5f79bf2f8f62aa39c"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
